---
title: Frisco Template
timezone: UTC
collections:
  menu:
    title: MENU
    output: true
  posts:
    title: Posts
    output: true
  staff_members:
    title: Staff Members
    output: false
    _hide_content: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    map:
      hello:
      - red
      - green
      - blue
- scope:
    path: contact-success.html
  values:
    layout: page
url: https://brave-submarine.cloudvent.net
baseurl: 
google_analytics_key: 
google_maps_javascript_api_key: 
disqus_shortname: 
logo: "/siteicon.png"
description: App marketing template for Jekyll.
author:
  name: 
  email: 
  twitter: 
social:
  name: Frisco Template
  links:
  - https://github.com/CloudCannon/frisco-jekyll-template
permalink: pretty
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-archives
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
paginate: 2
paginate_path: "/blog/:num/"
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Google Plus
- Instagram
- LinkedIn
- Pinterest
- Tumblr
- Twitter
- YouTube
- Email
- RSS
_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
